data:
    raw_file: data/census.csv
    data_path: data
model:
    file: model/model.pkl
    parameters:
        n_estimators: 100 
        max_depth: 3
        min_samples_leaf: 5
        random_state: 42
preprocessing:
    one_hot_encoder_file: model/oh_encoder.pkl
    label_encoder_file: model/label_encoder.pkl
    categories:
        - workclass
        - education
        - marital-status
        - occupation
        - relationship
        - race
        - sex
        - native-country
