services:
  # A Docker web service
  - type: web
    name: udacity-mlops-project4 
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: conda install --file conda_env_project4.yaml
    startCommand: ./start_uvicorn.sh
