services:
  # A Docker web service
  - type: web
    name: udacity-mlops-project4 
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    startCommand: uvicorn --app-dir src   main:app --reload
