# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [push]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        # caching pip dependencies
        cache: 'pip'
    - name: upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # if serious errors are encountered, stop building - check files in src and testing
        flake8 --count  --statistics  --show-source --select=E9,F63,F7,F82   src tests
        # do a broader test, but treat the encountered issues as warnings and continue bui8lding
        flake8 --count  --statistics  --show-source --exit-zero --max-complexity=10 --max-line-length=120   src tests
    - name: Perform pytest
      run: |
        export PYTHONPATH=$(pwd)/src
        pytest -v -p no:warnings  -o log_cli=true  --log-cli-level=INFO tests
    - name: Deploy
      # The Deploy step executes a curl request to our deploy hook URL only if the Test  with pytest step succeeded.
      # using hook to trigger the deployment only if test succeds, see https://docs.render.com/deploy-hooks for setting the secret
      env:
        deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      run: |
        curl "$deploy_url"
